CONTAINER Ohorope
{
	NAME Ohorope;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG HOROPE_RES     { MIN 2; MAX 150; MINSLIDER 2; MAXSLIDER 50; CUSTOMGUI LONGSLIDER; }
		REAL HOROPE_RAD     { UNIT METER; MIN 0.0; MINSLIDER 1.0; MAXSLIDER 50.0; CUSTOMGUI REALSLIDER; }
        LONG HOROPE_FSUB    { MIN 1; MAX 4; }
        LONG HOROPE_SEG     { MIN 3; MAX 16; }
        SEPARATOR {;}
        BOOL HOROPE_CTRL    {}
        BOOL HOROPE_SKIN     {}
        BOOL HOROPE_SKIN_ON  {}
	}
}
